# Generated by Django 4.2.4 on 2023-09-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='emg_fund',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='ret_fund',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
