# Generated by Django 4.2.4 on 2023-09-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESapp', '0002_user_age_user_emg_fund_user_ret_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newuser',
            field=models.BooleanField(default=True),
        ),
    ]
